- Added input validation on init - Updated error messages with useful information - Refactor transfer files code - Updated readme documentation and usage example

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -79,6 +79,9 @@ runs:
   using: "composite"
   steps:
     - run: |
+        echo "::group::Initialization"
+
+        echo "Check repository"
         if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" != "true" ]; then
           echo "::error::Git repository not found. Please ensure you have a checkout action step before this step."
           exit 1
@@ -86,11 +89,7 @@ runs:
 
         printf '%.s_' {1..50} > ~/hr && echo "" >> ~/hr
 
-        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-          echo "input_sync=${{ github.event.inputs.sync }}" >> ${GITHUB_ENV}
-        else
-          echo "input_sync=${{ inputs.sync }}" >> ${GITHUB_ENV}
-        fi
+        echo "Initialize inputs"
 
         remote_path_unslash=$(realpath --canonicalize-missing ${{ inputs.remote-path }})
         remote_path_slash="${remote_path_unslash}/"
@@ -110,6 +109,26 @@ runs:
         else
           echo "proxy_cmd=" >> ${GITHUB_ENV}
         fi
+
+        input_sync=${{ inputs.sync }}
+        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+          input_sync=${{ github.event.inputs.sync }}
+        fi
+        echo "input_sync=${input_sync}" >> ${GITHUB_ENV}
+
+        echo "Validate inputs"
+
+        if [ "${{ inputs.remote-protocol }}" != "sftp" ] && [ "${{ inputs.remote-protocol }}" != "ftp" ]; then
+          echo "::error::Invalid protocol: ${{ inputs.remote-protocol }}. Supported protocols are 'ftp' and 'sftp'."
+          exit 1
+        fi
+
+        if [ "${input_sync}" != "delta" ] && [ "${input_sync}" != "full" ]; then
+          echo "::error::Invalid synchronization: ${input_sync}. Supported types are 'delta' and 'full'."
+          exit 1
+        fi
+
+        echo "::endgroup::"
 
         exit 0
       shell: bash
@@ -190,7 +209,6 @@ runs:
         cat ~/hr
 
         echo "debug $([ "${{ inputs.debug }}" == "true" ] && echo "9" || echo "false")
-        set cmd:queue-parallel 5
         set ftp:ssl-protect-data true
         set ftp:sync-mode false
         set log:enabled/xfer true
@@ -242,8 +260,6 @@ runs:
         if [ "${{ env.input_sync }}" == "delta" ]; then
           echo "::group::Prepare files"
 
-          echo -e "Event: ${{ github.event_name }}\nCommitter: ${{ github.actor }}\nMessage: ${{ github.event.head_commit.message }}" && cat ~/hr
-
           touch ~/files-upload ~/files-delete
           echo ${{ github.sha }} > .deploy-revision
           git_depth=$(git rev-list --count --all)
@@ -257,13 +273,15 @@ runs:
             elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
               git_previous_commit=$(git rev-parse ${{ github.sha }}^)
             else
-              echo "::error::Only 'push', 'pull_request' and 'workflow_dispatch' events are supported for delta file synchronization."
+              echo "::error::Event not supported for delta synchronization: ${{ github.event_name }}. Supported events are 'push', 'pull_request' and 'workflow_dispatch'."
               exit 1
             fi
           else
-            echo "::error::No commit history found for delta file synchronization. Please ensure you have 'fetch-depth: 0' in checkout action."
+            echo "::error::Commit history not found for delta synchronization. Please ensure you have 'fetch-depth: 0' in checkout action."
             exit 1
           fi
+
+          echo -e "Event: ${{ github.event_name }}\nRevision: https://github.com/${{ github.repository }}/commit/${{ github.sha }}\nCommitter: ${{ github.actor }}\nMessage: ${{ github.event.head_commit.message }}\nPrevious Revision: https://github.com/${{ github.repository }}/commit/${git_previous_commit}" && cat ~/hr
 
           git diff --name-only --diff-filter=ACMRT ${git_previous_commit}..${{ github.sha }} | grep --ignore-case --invert-match "^\.git.*" > ~/files-upload && echo "File created: ~/files-upload" && cat ~/files-upload && cat ~/hr
           git diff --name-only --diff-filter=D ${git_previous_commit}..${{ github.sha }} | grep --ignore-case --invert-match "^\.git.*" > ~/files-delete && echo "File created: ~/files-delete" && cat ~/files-delete && cat ~/hr
@@ -281,29 +299,28 @@ runs:
         Local path: ${{ inputs.local-path }}
         Remote path: ${{ env.remote_path_unslash }}"
 
-        touch .deploy-running
-
         if [ "${{ env.input_sync }}" == "delta" ]; then
           echo -e "Upload files: $(grep -c ^ ~/files-upload)\nDelete files: $(grep -c ^ ~/files-delete)"
         fi
 
-        if [ "${{ inputs.remote-protocol }}" != "sftp" ] && [ "${{ inputs.remote-protocol }}" != "ftp" ]; then
-          echo "::error::Protocol not supported: ${{ inputs.remote-protocol }}"
-          exit 1
-        fi
-
         cat ~/hr
+
+        touch .deploy-running
 
         if [ "${{ env.input_sync }}" == "full" ]; then
           ${{ env.proxy_cmd }} lftp -c "open ${{ inputs.remote-protocol }}://${{ inputs.remote-user }}@${{ inputs.remote-host }}:${{ inputs.remote-port }}
-            mirror --exclude-glob=.git*/ --max-errors=10 --reverse --verbose=1 ${{ inputs.ftp-mirror-options }} ${{ inputs.local-path }} ${{ env.remote_path_unslash }}"
+            put -O \"${{ env.remote_path_unslash }}\" .deploy-running
+            mirror --exclude-glob=.git*/ --max-errors=10 --reverse ${{ inputs.ftp-mirror-options }} ${{ inputs.local-path }} ${{ env.remote_path_unslash }}
+            rm -f \"${{ env.remote_path_slash }}.deploy-running\""
         else
           ${{ env.proxy_cmd }} lftp -c "open ${{ inputs.remote-protocol }}://${{ inputs.remote-user }}@${{ inputs.remote-host }}:${{ inputs.remote-port }}
-            mput -c -d -O \"${{ env.remote_path_unslash }}\" .deploy-running .deploy-revision $(awk 'ORS=" " { print "\"" $0 "\"" }' ~/files-upload)
-            rm -f \"${{ env.remote_path_slash }}.deploy-running\" $(awk 'ORS=" " { print "\"${{ env.remote_path_slash }}" $0 "\"" }' ~/files-delete)"
-
-          [ -f ~/.transfer_log ] && cat ~/.transfer_log
+            put -O \"${{ env.remote_path_unslash }}\" .deploy-running
+            mput -c -d -O \"${{ env.remote_path_unslash }}\" .deploy-revision $(awk 'ORS=" " { print "\"" $0 "\"" }' ~/files-upload)
+            rm -f \"${{ env.remote_path_slash }}.deploy-check\" $(awk 'ORS=" " { print "\"${{ env.remote_path_slash }}" $0 "\"" }' ~/files-delete)
+            rm -f \"${{ env.remote_path_slash }}.deploy-running\""
         fi
+
+        [ -f ~/.transfer_log ] && cat ~/.transfer_log
 
         echo "::endgroup::"
 
