General code updates - Updated SSH and FTP configuration - Refactor transfer files code - Close proxy SSH connection on cleanup - Updated readme documentation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,6 +1,6 @@
 name: 'FTP/SFTP file deployer'
 
-description: 'Composite GitHub Action (Linux runner) for deploying repository content to remote host.'
+description: 'Fast and customizable deployment with proxy support. Deploy only changed files or do full sync/mirror of repository content.'
 
 branding:
   icon: "upload"  
@@ -184,9 +184,7 @@ runs:
             tcp_connect_time_out 10000
             [ProxyList]
             socks5 127.0.0.1 ${{ inputs.proxy-forwarding-port }}" > ${config_proxychains} && echo "File created: ${config_proxychains}"
-            if [ "${{ inputs.debug }}" == "true" ]; then
-              cat ${config_proxychains}
-            fi
+            [ "${{ inputs.debug }}" == "true" ] && cat ${config_proxychains}
             cat ~/hr
           else
             echo "input_proxy=false" >> ${GITHUB_ENV}
@@ -195,17 +193,13 @@ runs:
         fi
 
         config_ssh=~/.ssh/config
-        mkdir ~/.ssh && echo "StrictHostKeyChecking=no" > ${config_ssh} && chmod 600 ${config_ssh} && echo "File created: ${config_ssh}"
-        if [ "${{ inputs.debug }}" == "true" ]; then
-          cat ${config_ssh}
-        fi
+        mkdir ~/.ssh && echo -e "ExitOnForwardFailure=yes\nStrictHostKeyChecking=no" > ${config_ssh} && chmod 600 ${config_ssh} && echo "File created: ${config_ssh}"
+        [ "${{ inputs.debug }}" == "true" ] && cat ${config_ssh}
         cat ~/hr
 
         netrc=~/.netrc
         echo "machine ${{ inputs.remote-host }} login ${{ inputs.remote-user }} password ${{ env.input_remote_password }}" > ${netrc} && chmod 600 ${netrc} && echo "File created: ${netrc}"
-        if [ "${{ inputs.debug }}" == "true" ]; then
-          cat ${netrc}
-        fi
+        [ "${{ inputs.debug }}" == "true" ] && cat ${netrc}
         cat ~/hr
 
         echo "debug $([ "${{ inputs.debug }}" == "true" ] && echo "9" || echo "false")
@@ -229,10 +223,9 @@ runs:
         else
           echo "set sftp:connect-program /usr/bin/ssh -a -x ${{ inputs.ssh-options }}" >> ~/.lftprc
         fi
+        echo "open ${{ inputs.remote-protocol }}://${{ inputs.remote-user }}@${{ inputs.remote-host }}:${{ inputs.remote-port }}" >> ~/.lftprc
         echo "File created: ~/.lftprc"
-        if [ "${{ inputs.debug }}" == "true" ]; then
-          cat ~/.lftprc
-        fi
+        [ "${{ inputs.debug }}" == "true" ] && cat ~/.lftprc
 
         echo "::endgroup::"
 
@@ -283,6 +276,10 @@ runs:
 
           echo -e "Event: ${{ github.event_name }}\nRevision: https://github.com/${{ github.repository }}/commit/${{ github.sha }}\nCommitter: ${{ github.actor }}\nMessage: ${{ github.event.head_commit.message }}\nPrevious Revision: https://github.com/${{ github.repository }}/commit/${git_previous_commit}" && cat ~/hr
 
+          # ${{ env.proxy_cmd }} lftp -c "set log:enabled/xfer false; get -O ~ \"${{ env.remote_path_slash }}.deploy-revision\"; exit 0"
+          # echo -n "Remote Revision: " && [ -f ~/.deploy-revision ] && cat ~/.deploy-revision || echo ""
+          # cat ~/hr
+
           git diff --name-only --diff-filter=ACMRT ${git_previous_commit}..${{ github.sha }} | grep --ignore-case --invert-match "^\.git.*" > ~/files-upload && echo "File created: ~/files-upload" && cat ~/files-upload && cat ~/hr
           git diff --name-only --diff-filter=D ${git_previous_commit}..${{ github.sha }} | grep --ignore-case --invert-match "^\.git.*" > ~/files-delete && echo "File created: ~/files-delete" && cat ~/files-delete && cat ~/hr
 
@@ -308,13 +305,11 @@ runs:
         touch .deploy-running
 
         if [ "${{ env.input_sync }}" == "full" ]; then
-          ${{ env.proxy_cmd }} lftp -c "open ${{ inputs.remote-protocol }}://${{ inputs.remote-user }}@${{ inputs.remote-host }}:${{ inputs.remote-port }}
-            put -O \"${{ env.remote_path_unslash }}\" .deploy-running
+          ${{ env.proxy_cmd }} lftp -c "put -O \"${{ env.remote_path_unslash }}\" .deploy-running
             mirror --exclude-glob=.git*/ --max-errors=10 --reverse ${{ inputs.ftp-mirror-options }} ${{ inputs.local-path }} ${{ env.remote_path_unslash }}
             rm -f \"${{ env.remote_path_slash }}.deploy-running\""
         else
-          ${{ env.proxy_cmd }} lftp -c "open ${{ inputs.remote-protocol }}://${{ inputs.remote-user }}@${{ inputs.remote-host }}:${{ inputs.remote-port }}
-            put -O \"${{ env.remote_path_unslash }}\" .deploy-running
+          ${{ env.proxy_cmd }} lftp -c "put -O \"${{ env.remote_path_unslash }}\" .deploy-running
             mput -c -d -O \"${{ env.remote_path_unslash }}\" .deploy-revision $(awk 'ORS=" " { print "\"" $0 "\"" }' ~/files-upload)
             rm -f \"${{ env.remote_path_slash }}.deploy-check\" $(awk 'ORS=" " { print "\"${{ env.remote_path_slash }}" $0 "\"" }' ~/files-delete)
             rm -f \"${{ env.remote_path_slash }}.deploy-running\""
@@ -328,6 +323,10 @@ runs:
       shell: bash
     - run: |
         echo "::group::Cleanup"
+
+        if [ "${{ env.input_proxy }}" == "true" ]; then
+          sudo pkill ssh
+        fi
 
         rm --force --verbose ~/.netrc ~/proxy_private_key_file ~/ssh_private_key_file
 
